bookstore/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'books/(?P<book_id>\d+)/$',views.detail,name='detail'),
	url(r'list/(?P<type_id>\d+)/(?P<page>\d+)/$',views.list,name='list'),

]

bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^user/', include('users.urls', namespace='user')),
	url(r'^tinymce/', include('tinymce.urls')),  # 在项目路由中配置编辑器的路由
	url(r'^', include('books.urls', namespace='books')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^order/', include('order.urls', namespace='order')),
	url(r'^comment/',include('comments.urls',namespace='comment')),
	url(r'^search/',include('haystack.urls')),
]

bookstore/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^add/$',views.cart_add,name='add'),
	url(r'^count/$',views.cart_count,name='count'),
	url(r'^$',views.cart_show,name='show'),
	url(r'^del/$',views.cart_del,name='delete'),
	url(r'^update/$',views.cart_update,name='update'),
]

bookstore/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
	url(r'^register/$', views.register, name='register'),
	url(r'^register_handle/$', views.register_handle, name='register_handle'),
	url(r'^login/$', views.login, name='login'),
	url(r'^login_check/$', views.login_check, name='login_check'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^$', views.user, name='user'),
	url(r'^address/$',views.address,name='address'),
	url(r'^order/$',views.order,name='order'),
	url(r'^verifycode/$',views.verifycode,name='verifycode'),
	url(r'^active/(?P<token>.*)/$',views.register_active,name='active'),
]

bookstore/users/models.py
from django.db import models
from db.base_model import BaseModel
from utils.get_hash import get_hash


# Create your models here.


# 自定义模型类管理器,添加额外方法
class PassportManager(models.Manager):
	# 添加一个账户信息
	def add_one_passport(self, username, password, email):
		passport = self.create(username=username, password=get_hash(password), email=email)
		return passport

	# 根据用户名和密码查找账户信息
	def get_one_passport(self, username, password):
		try:
			passport = self.get(username=username, password=get_hash(password))
		except self.model.DoesNotExist:
			passport = None
		return passport

	def check_passport(self, username):
		try:
			passport = self.get(username=username)
		except self.model.DoesNotExist:
			passport = None
		if passport:
			return True
		return False


# 定义用户模型类
class Passport(BaseModel):
	username = models.CharField(max_length=20, verbose_name='用户名称')
	password = models.CharField(max_length=40, verbose_name='用户密码')
	email = models.EmailField(verbose_name='用户邮箱')
	is_active = models.BooleanField(default=False, verbose_name='激活状态')

	# 重写模型类的管理器
	objects = PassportManager()

	def __str__(self):
		return self.username

	class Meta:
		db_table = 's_user_account'


# 定义地址模型管理器
class AddressManager(models.Manager):
	# 根据账户id找到默认的收货地址
	def get_default_address(self, passport_id):
		try:
			addr = self.get(passport_id=passport_id, is_default=True)
		except self.model.DoesNotExist:
			addr = None
		return addr

	# 添加一个新的收货地址
	def add_one_address(self, passport_id, recipient_name, recipient_addr, zip_code, recipient_phone):
		# 判断一个用户是否拥有默认收货信息
		addr = self.get_default_address(passport_id=passport_id)
		if addr:
			# 存在默认地址,False
			is_default = False
		else:
			# 不存在默认地址,True
			is_default = True

		# 新建一个收货地址信息
		addr = self.create(
			passport_id=passport_id,
			recipient_name=recipient_name,
			recipient_addr=recipient_addr,
			zip_code=zip_code,
			recipient_phone=recipient_phone,
			is_default=is_default
		)
		return addr


class Address(BaseModel):
	recipient_name = models.CharField(max_length=20, verbose_name='收件人')
	recipient_addr = models.CharField(max_length=256, verbose_name='收件地址')
	zip_code = models.CharField(max_length=6, verbose_name='邮政编码')
	recipient_phone = models.CharField(max_length=11, verbose_name='联系电话')
	is_default = models.BooleanField(default=False, verbose_name='是否默认')
	passport = models.ForeignKey('Passport', verbose_name='账户')

	objects = AddressManager()

	class Meta:
		db_table = 's_user_address'

bookstore/users/views.py
import re
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from .models import Passport, Address
from django.core.urlresolvers import reverse
from utils.get_hash import get_hash
from utils.decorators import login_required
from order.models import OrderInfo, OrderGoods
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
# itsdangerous是一个产生token的库
from bookstore import settings
from django.core.mail import send_mail
from django_redis import get_redis_connection
from books.models import Books


# Create your views here.


# 调用账户注册页面
def register(request):
	return render(request, 'users/register.html')


# 进行用户注册处理
def register_handle(request):
	# 接收表单提交数据
	username = request.POST.get('user_name')
	password = request.POST.get('pwd')
	email = request.POST.get('email')

	# 校验数据是否齐全
	if not all([username, password, email]):
		return render(request, 'users/register.html', {'errmsg': '参数不能为空.'})

	# 校验邮箱是否合法
	if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
		return render(request, 'users/register.html', {'errmsg': '邮箱不合法.'})

	p = Passport.objects.check_passport(username=username)

	if p:
		return render(request, 'users/register.html', {'errmsg': '用户名已存在!'})

	# 进行业务处理:注册,向账户系统中添加账户
	passport = Passport.objects.add_one_passport(username=username, password=password, email=email)
	# passport.save()

	serializer = Serializer(settings.SECRET_KEY, 3600)
	token = serializer.dumps({'confirm': passport.id})
	token = token.decode()

	send_mail('尚硅谷书城用户激活', '', settings.EMAIL_FROM, [email],
			  html_message='<a href="http://127.0.0.1:8000/user/active/%s/">http://127.0.0.1:8000/user/active/</a>' % token)

	return redirect(reverse('books:index'))


# 用户账户激活
def register_active(request,token):
	serializer = Serializer(settings.SECRET_KEY,3600)
	try:
		info = serializer.loads(token)
		passport_id = info['confirm']
		passport = Passport.objects.get(id=passport_id)
		passport.is_active = True
		passport.save()
		return redirect(reverse('user:login'))
	except SignatureExpired:
		return HttpResponse('激活链接已经过期')


# 显示登录页面
def login(request):
	username = ''
	checked = ''
	context = {
		'username': username,
		'checked': checked,
	}
	return render(request, 'users/login.html', context)


def login_check(request):
	# 获取表单提交的数据
	username = request.POST.get('username')
	password = request.POST.get('password')
	remember = request.POST.get('remember')
	verifycode = request.POST.get('verifycode')

	# 数据校验
	if not all([username, password, remember, verifycode]):
		return JsonResponse({'code': 0, 'errmsg': '数据不完整'})

	if verifycode.upper() != request.session['verifycode']:
		return JsonResponse({'code': 1, 'errmsg': '验证码错误'})

	# 根据用户名和密码查找账户信息
	passport = Passport.objects.get_one_passport(username=username, password=password)
	# 如果用户名和密码都正确的话
	if passport:
		response = {
			'next_url': reverse('books:index'),
			'code': 200,
		}
		jres = JsonResponse(response)

		if remember == 'true':
			jres.set_cookie('username', username, max_age=7 * 24 * 3600)
		else:
			jres.delete_cookie('username')

		# 记住用户登录状态
		request.session['islogin'] = True
		request.session['username'] = username
		request.session['passport_id'] = passport.id
		return jres
	else:
		return JsonResponse({'code': 500})


def logout(request):
	request.session.flush()
	return redirect(reverse('books:index'))


# 调取用户信息页面的函数
@login_required
def user(request):
	# 获取账户id
	passport_id = request.session.get('passport_id')
	# 根据账户id获取账户的默认地址信息
	addr = Address.objects.get_default_address(passport_id=passport_id)

	# 获取用户的最近浏览信息
	con = get_redis_connection('default')
	key = 'history_%d' % passport_id
	# 取出用户最近浏览的5个商品的id
	history_li = con.lrange(key,0,4)
	# 将这五本书遍历取出放入列表,渲染到前端
	books_li = []
	for id in history_li:
		books = Books.objects.get_books_by_id(books_id=id)
		books_li.append(books)

	context = {
		'addr': addr,
		'page': 'user',
		'books_li': books_li,
	}
	return render(request, 'users/user_center_info.html', context)


# 用户中心-地址页
@login_required
def address(request):
	# 获取登录用户的id
	passport_id = request.session.get('passport_id')

	if request.method == 'GET':
		addr = Address.objects.get_default_address(passport_id=passport_id)
		return render(request, 'users/user_center_site.html', {'addr': addr, 'page': address})
	else:
		# 添加收货地址
		# 1.接收数据
		recipient_name = request.POST.get('username')
		recipient_addr = request.POST.get('addr')
		zip_code = request.POST.get('zip_code')
		recipient_phone = request.POST.get('phone')

		# 2.进行校验
		if not all([recipient_name, recipient_addr, zip_code, recipient_phone]):
			return render(request, 'users/user_center_site.html', {'errmsg': '参数不能为空'})

		# 3.添加收货地址
		Address.objects.add_one_address(
			passport_id=passport_id,
			recipient_name=recipient_name,
			recipient_addr=recipient_addr,
			zip_code=zip_code,
			recipient_phone=recipient_phone
		)

		# 4.返回应答
		return redirect(reverse('user:address'))


@login_required
def order(request):
	# 查询用户的id
	passport_id = request.session.get('passport_id')

	# 获取订单信息
	order_li = OrderInfo.objects.filter(passport_id=passport_id)

	# 遍历订单获取商品信息
	for order in order_li:
		# 根据订单id查询订单商品信息
		order_id = order.order_id
		order_books_li = OrderGoods.objects.filter(order_id=order_id)

		# 计算商品的小计
		for order_books in order_books_li:
			count = order_books.count
			price = order_books.price
			amount = count * price
			order_books.amount = amount

		# 给order对象动态增加一个属性order_books_li,保存订单中商品的信息
		order.order_books_li = order_books_li

	context = {
		'order_li': order_li,
		'page': 'order'
	}

	return render(request, 'users/user_center_order.html', context)


def verifycode(request):
	# 引入绘图模块
	from PIL import Image, ImageDraw, ImageFont
	# 引入随机模块
	import random

	# 定义变量,用于画面的背景色,宽,高
	bgcolor = (random.randrange(20, 100), random.randrange(20, 100), 255)
	width = 100
	height = 25

	# 创建画面对象(也就是最终显示的验证码图片)
	im = Image.new('RGB', (width, height), bgcolor)

	# 创建画笔对象,该画笔对象将在im画面对象上进行绘制
	draw = ImageDraw.Draw(im)

	# 调用画笔的point()函数绘制噪点
	for i in range(0, 100):
		# 噪点的坐标
		xy = (random.randrange(0, width), random.randrange(0, height))
		# 噪点的颜色
		fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
		# 绘制
		draw.point(xy, fill=fill)

	# 定义验证码的备选值
	str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'

	# 随机选取4个值作为验证码
	rand_str = ''
	for i in range(0, 4):
		rand_str += str1[random.randrange(0, len(str1))]

	# 构造字体对象
	font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', 15)

	# 构造字体颜色
	fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))

	# 绘制4个字
	# 参数:字符串左上角坐标,要写入的字符串,
	draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
	draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
	draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
	draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)

	# 释放画笔
	del draw

	# 将生产的验证码字符串存入session,用于做进一步的验证
	request.session['verifycode'] = rand_str

	# 内存文件操作
	import io
	# 实例一个读写二进制文件的对象
	buf = io.BytesIO()
	# 将图片保存在内存中,文件类型为png
	im.save(buf, 'png')
	# 将内存中的图片数据返回给客户端,MIME类型为图片png
	return HttpResponse(buf.getvalue(), 'image/png')

bookstore/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-登录{% endblock title %}
{% block topfiles %}{% endblock topfiles %}
{% block header_content %}{% endblock header_content %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
<div class="login_top clearfix">
    <a href="{% url 'books:index' %}" class="login_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
</div>
<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">学计算机 · 来尚硅谷</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url 'user:register' %}">立即注册</a>
            </div>
            <div class="form_input">
{#                    在前端编写一段发送ajax post请求的html代码和jquery代码#}
                <form>
                    {% csrf_token %}
                    <input type="text" id="username" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
                    <div class="user_error">输入错误</div>
                    <input type="password" id="password" name="password" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div style="top: 100px;position:absolute;">
                        <input style="width: 80px" type="text" id="vc" name="vc">
                        <img id='verifycode' src="/user/verifycode/" alt="CheckCode" onclick="this.src='/user/verifycode/?'+Math.random()">
                    </div>
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" value="{{ checked }}">
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                    </div>
                    <input type="submit" id="submit" name="" value="登录" class="input_submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

{% block cart_count %}{% endblock cart_count %}

{% block bottomfiles %}
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script>
$(function () {
   $('#submit').click(function (e) {
        e.preventDefault();
        //获取用户名和密码
        var username = $('#username').val();
        var password = $('#password').val();
        var csrf = $('input[name="csrfmiddlewaretoken"]').val();
        var remember = $('input[name="remember"]').prop('checked');
        var vc = $('input[name="vc"]').val();
        var data = {
            'username':username,
            'password':password,
            'csrfmiddlewaretoken':csrf,
            'remember':remember,
            'verifycode':vc
        };
        //发起ajax请求
        //res是后端的方法返回的数据
        $.post('{% url 'user:login_check' %}',data,function(res) {
            if (res.code == 200){
                location.href = res.next_url
            }
            else if(res.code == 0){
                $('#username').prev().html(res.errmsg).show()
            }
            else if(res.code == 1){
                $('#username').next().html(res.errmsg).show()
            }
            else if(res.code == 500){
                $('#username').next().html('用户名或密码错误').show()
            }
        })
    })
})
</script>
{% endblock bottomfiles %}

bookstore/templates/users/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-注册{% endblock title %}
{% block header_content %}{% endblock header_content %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
<div class="register_con">
    <div class="l_con fl">
        <a class="reg_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
        <div class="reg_slogan">学计算机  ·  来尚硅谷</div>
        <div class="reg_banner"></div>
    </div>
    <div class="r_con fr">
        <div class="reg_title clearfix">
            <h1>用户注册</h1>
            <a href="{% url 'user:login' %}">登录</a>
        </div>
        <div class="reg_form clearfix">
            <form method="post" action="{% url 'user:register_handle' %}">
                {% csrf_token %}
                {{ errmsg }}
            <ul>
                <li>
                    <label>用户名:</label>
                    <input type="text" name="user_name" id="user_name">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>密码:</label>
                    <input type="password" name="pwd" id="pwd">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>确认密码:</label>
                    <input type="password" name="cpwd" id="cpwd">
                    <span class="error_tip">提示信息</span>
                </li>
                <li>
                    <label>邮箱:</label>
                    <input type="text" name="email" id="email">
                    <span class="error_tip">提示信息</span>
                </li>
                <li class="agreement">
                    <input type="checkbox" name="allow" id="allow" checked="checked">
                    <label>同意”尚硅谷书城用户使用协议“</label>
                    <span class="error_tip2">提示信息</span>
                </li>
                <li class="reg_sub">
                    <input type="submit" value="注 册" name="">
                </li>
            </ul>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

{% block cart_count %}{% endblock cart_count %}

bookstore/templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-用户中心{% endblock title %}
{% block topfiles %}{% endblock topfiles %}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'books:index' %}" class="logo fl"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<form method="get" action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q">
                <input type="submit" class="input_btn fr" value="查询">
            </form>
		</div>
	</div>
{% endblock search_bar %}

{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ request.session.username }}</li>
                    {% if addr %}
                        <li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
                        <li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
                    {% else %}
                        <li><span>联系方式：</span>无</li>
                        <li><span>联系地址：</span>无</li>
                    {% endif %}
                </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="book_type_list clearfix">
                    {% for book in books_li %}
                    <li>
                        <a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
                        <h4><a href="{% url 'books:detail'  book_id=book.id %}">{{ book.name }}</a></h4>
                        <div class="operate">
                            <span class="price">￥{{ book.price }}</span>
                            <span class="unit">/{{ book.unit }}</span>
                            <a href="#" class="add_book" title="加入购物车"></a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
		</div>
	</div>
{% endblock body %}

bookstore/templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filters %}
{% block title %}尚硅谷书城-用户中心{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}

{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'books:index' %}" class="logo fl"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<form method="get" action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q">
                <input type="submit" class="input_btn fr" value="查询">
            </form>
		</div>
	</div>
{% endblock search_bar %}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            {% csrf_token %}
            <h3 class="common_title2">全部订单</h3>
            {% for order in order_li %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.order_id }}</li>
                <li class="col02 stress">{{ order.status }}</li>
            </ul>

            <table class="order_list_table w980">
                <tbody>
                    <tr>
                        <td width="55%">
                            <ul class="order_book_list clearfix">
                                {% for order_books in order.order_books_li %}
                                <li class="col01"><img src="{% static order_books.books.image %}"></li>
                                <li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price }}元/册</em></li>
                                <li class="col03">{{ order_books.count }}</li>
                                <li class="col04">{{ order_books.amount }}元</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td width="15%">{{ order.total_price }}元</td>
                        <td width="15%">{{ order.status | order_status }}</td>
                        <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                    </tr>
                </tbody>
            </table>

            {% endfor %}
            <div class="pagenation">
                <a href="#"><上一页</a>
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
                <a href="#">下一页></a>
            </div>
		</div>
	</div>
{% endblock body %}

{% block bottomfiles %}
    <script>
    $(function () {
        $('.oper_btn').click(function () {
            order_id = $(this).attr('order_id');
            order_status = $(this).attr('order_status');
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            params = {
                'order_id':order_id,
                'csrfmiddlewaretoken':csrf
            };
            if(order_status == 1){
                $.post('/order/pay/',params,function (data) {
                    if(data.res == 3){
                        window.open(data.pay_url);
                        $.post('/order/check_pay/',params,function (data) {
                            if(data.res == 3){
                                alert('支付成功');
                                location.reload()
                            }
                            else {
                                alert(data.errmsg)
                            }
                        })
                    }
                    else {
                        alert(data.errmsg)
                    }
                })
            }
        })
    })
    </script>
{% endblock bottomfiles %}




bookstore/templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-用户中心{% endblock title %}
{% block topfiles %}{% endblock topfiles %}
{% block search_bar %}
    	<div class="search_bar clearfix">
		<a href="{% url 'books:index' %}" class="logo fl"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<form method="get" action="/search/" target="_blank">
                <input type="text" class="input_text fl" name="q">
                <input type="submit" class="input_btn fr" value="查询">
            </form>
		</div>
	</div>
{% endblock search_bar %}

{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if addr %}
						    <dd>{{ addr.recipient_addr }} （{{ addr.recipient_name }} 收） {{ addr.recipient_phone }}</dd>
                        {% else %}
                            <dd>无</dd>
                        {% endif %}
					</dl>					
				</div>

				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="/user/address/">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>
						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}