bookstore/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'books/(?P<book_id>\d+)/$',views.detail,name='detail'),
	url(r'list/(?P<type_id>\d+)/(?P<page>\d+)/$',views.list,name='list'),

]

bookstore/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^user/', include('users.urls', namespace='user')),
	url(r'^tinymce/', include('tinymce.urls')),  # 在项目路由中配置编辑器的路由
	url(r'^', include('books.urls', namespace='books')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^order/', include('order.urls', namespace='order')),
	url(r'^comment/',include('comments.urls',namespace='comment')),
	url(r'^search/',include('haystack.urls')),
]

bookstore/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^add/$',views.cart_add,name='add'),
	url(r'^count/$',views.cart_count,name='count'),
	url(r'^$',views.cart_show,name='show'),
	url(r'^del/$',views.cart_del,name='delete'),
	url(r'^update/$',views.cart_update,name='update'),
]

bookstore/books/models.py
from django.db import models
from tinymce.models import HTMLField
from db.base_model import BaseModel
from books.enums import *
from django.core.files.storage import FileSystemStorage
fs = FileSystemStorage(location='/root/test_bookstore/bookstore/collect_static')

# Create your models here.


# 自定义模型类管理器,添加额外方法
class BooksManager(models.Manager):
	# 根据商品类型的id查询商品信息
	def get_books_by_type(self, type_id, limit=None, sort='default'):
		if sort == 'new':
			order_by = ('-create_time',)
		elif sort == 'hot':
			order_by = ('-sales',)
		elif sort == 'price':
			order_by = ('price',)
		else:
			order_by = ('-pk',)

		# 根据书籍类型id和排序类型得到书籍列表
		books_li = self.filter(type_id=type_id).order_by(*order_by)

		# 获取排序好的书籍列表后进行切片
		if limit:
			books_li = books_li[:limit]
		return books_li

	# 根据书籍的id查询到书籍
	def get_books_by_id(self, books_id):
		try:
			book = self.get(id=books_id)
		except self.model.DoesNotExist:
			book = None
		return book


# 商品模型类
class Books(BaseModel):
	books_type_choices = ((k, v) for k, v in BOOKS_TYPE.items())
	status_choices = ((k, v) for k, v in STATUS_CHOICE.items())
	# 设置了choices的字段将构成一个二项元祖的可迭代对象,在后台中显示为下拉列表框,元组第二项目将作为value展示
	type_id = models.SmallIntegerField(default=PYTHON, choices=books_type_choices, verbose_name='商品种类')
	name = models.CharField(max_length=20, verbose_name='商品名称')
	desc = models.CharField(max_length=128, verbose_name='商品简介')
	price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
	unit = models.CharField(max_length=20, verbose_name='商品单位')
	stock = models.IntegerField(default=1, verbose_name='商品库存')
	sales = models.IntegerField(default=0, verbose_name='商品销量')
	detail = HTMLField(verbose_name='商品详情')
	image = models.ImageField(storage=fs,upload_to='books', verbose_name='商品图片')
	status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')

	# 自定义模型类管理器
	objects = BooksManager()

	def __str__(self):
		return self.name

	class Meta:
		db_table = 's_books'
		verbose_name = '书籍'
		verbose_name_plural = verbose_name

bookstore/books/views.py
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from books.models import Books
from books.enums import *
from django.views.decorators.cache import cache_page
from django_redis import get_redis_connection


# Create your views here.


# 显示首页
# 使用redis缓存首页页面
# @cache_page(60*15)
def index(request):
	# 查询每个种类的3个新品和4个销量最好的商品
	python_new = Books.objects.get_books_by_type(PYTHON, 3, sort='new')
	python_hot = Books.objects.get_books_by_type(PYTHON, 4, sort='hot')
	javascript_new = Books.objects.get_books_by_type(JAVASCRIPT, 3, sort='new')
	javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT, 4, sort='hot')
	algorithms_new = Books.objects.get_books_by_type(ALGORITHMS, 3, sort='new')
	algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS, 4, sort='hot')
	machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING, 3, sort='new')
	machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING, 4, sort='hot')
	operatingsystem_new = Books.objects.get_books_by_type(OPERATINGSYSTEM, 3, sort='new')
	operatingsystem_hot = Books.objects.get_books_by_type(OPERATINGSYSTEM, 4, sort='hot')
	database_new = Books.objects.get_books_by_type(DATABASE, 3, sort='new')
	database_hot = Books.objects.get_books_by_type(DATABASE, 4, sort='hot')

	# 定义模板上下文
	context = {
		'python_new': python_new,
		'python_hot': python_hot,
		'javascript_new': javascript_new,
		'javascript_hot': javascript_hot,
		'algorithms_new': algorithms_new,
		'algorithms_hot': algorithms_hot,
		'machinelearning_new': machinelearning_new,
		'machinelearning_hot': machinelearning_hot,
		'operatingsystem_new': operatingsystem_new,
		'operatingsystem_hot': operatingsystem_hot,
		'database_new': database_new,
		'database_hot': database_hot,
	}
	return render(request, 'books/index.html', context)


# 商品详情页面
def detail(request, book_id):
	# 根据书籍id找到书籍
	book = Books.objects.get_books_by_id(books_id=book_id)
	# 如果书籍不存在就回到首页
	if book is None:
		return redirect(reverse('books:index'))

	# 如果书籍存在根据书籍的类型id找到那一类型的所有数,并且获取两本最新上架的书
	books_li = Books.objects.get_books_by_type(type_id=book.type_id, limit=2, sort='new')

	if request.session.has_key('islogin'):
		# 用户已经登录,记录浏览记录
		con = get_redis_connection('default')
		key = 'history_%d' % request.session.get('passport_id')
		# 先从redis列表中移除book.id
		con.lrem(key, 0, book.id)
		con.lpush(key, book.id)
		# 保存用户最近浏览的5个商品
		con.ltrim(key, 0, 4)

	# 将这本数和新书列表渲染到书籍详情页面
	context = {'book': book, 'books_li': books_li}
	return render(request, 'books/detail.html', context)


# 商品列表页面
def list(request, type_id, page):
	# 获取排序方式(默认/价格/热度)
	sort = request.GET.get('sort', 'default')

	# 判断书籍类型是否合法
	if int(type_id) not in BOOKS_TYPE.keys():
		return redirect(reverse('books:index'))

	# 根据书籍类型id获取和排序方式获取书籍列表
	books_li = Books.objects.get_books_by_type(type_id=type_id, sort=sort)

	# 根据获得的书籍列表生成分页实例对象,每页有1条数据
	paginator = Paginator(books_li, 1)
	# 获取分页后的总页数
	num_pages = paginator.num_pages

	# 判断当前页码数(如果为空或者大于总页数,那就返回第一页)
	if page == '' or int(page) > num_pages:
		page = 1
	else:
		page = int(page)

	# 获取指定页码数的页面对象
	books_li = paginator.page(page)
	print(books_li)
	print(type(books_li))
	for book in books_li:
		print(type(book))
		print(book.price)

	# 总页数小于5,显示所有页码
	# range函数计数范围不包括stop
	if num_pages < 5:
		# [1,...,num_pages]
		pages = range(1, num_pages + 1)
	# 当前页是前3页,显示前5页
	elif page <= 3:
		pages = range(1, 6)
	# 当前页是后3页,显示后5页
	elif num_pages - page <= 2:
		pages = range(num_pages - 4, num_pages + 1)
	# 其他情况显示前2页,当前页,后2页
	else:
		pages = range(page - 2, page + 3)

	# 获取新品推荐书籍列表
	books_new = Books.objects.get_books_by_type(type_id=type_id, limit=2, sort='new')

	# 获取书籍类名
	type_title = BOOKS_TYPE[int(type_id)]

	# 定义上下文
	context = {
		'books_li': books_li,
		'books_new': books_new,
		'type_id': type_id,
		'sort': sort,
		'type_title': type_title,
		'pages': pages,
	}

	return render(request, 'books/list.html', context)

bookstore/templates/books/detail.html
{% extends 'books/list.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-商品详情{% endblock title %}
{% block topfiles %}
<style type="text/css">
    .comment{
        background-color: #c40000;
        color:#fff;
        margin-left: 10px;
        position: relative;
        z-index: 10;
        display: inline-block;
        width: 178px;
        height: 38px;
        border:1px solid #c40000;
        font-size: 14px;
        line-height: 38px;
        text-align: center;
    }
</style>
<script>
$(function () {
    // 计算总价
    update_total_price();
    function update_total_price() {
        //获取商品的数量和价格
        books_price = $('.show_price').children('em').text();
        books_count = $('.num_show').val();
        //计算商品的总价
        books_price = parseFloat(books_price);
        books_count = parseInt(books_count);
        total_price = books_price * books_count;
        //设置商品总价
        $('.total').children('em').text(total_price.toFixed(2) + '元')
    }

    //商品增加按钮点击事件
    $('.add').click(function () {
        //获取商品的数量
        books_count = $('.num_show').val();
        //加1
        books_count = parseInt(books_count) + 1;
        //重新设置值
        $('.num_show').val(books_count);
        //计算总价
        update_total_price()
    });

    //商品减少按钮点击事件
    $('.minus').click(function () {
        //获取商品的数量
        books_count = $('.num_show').val();
        //减1
        books_count = parseInt(books_count) - 1;
        if (books_count == 0){
            books_count = 1
        }
        //重新设置值
        $('.num_show').val(books_count);
        //计算总价
        update_total_price()
    });

    //手动输入
    $('.num_show').blur(function () {
        //获取商品得的数量
        books_count = $(this).val();
        //数据校验(为非数字,去空格后为0,数量小于等于0)
        if(isNaN(books_count) || books_count.trim().length == 0 || parseInt(books_count) <= 0){
            books_count = 1
        }
        $('.num_show').val(parseInt(books_count));
        update_total_price()
    })
})
</script>
{% endblock topfiles %}
{% block body %}
<div class="breadcrumb">
    <a href="#">全部分类</a>
    <span>></span>
    <a href="#">Python</a>
    <span>></span>
    <a href="#">商品详情</a>
</div>
<div class="book_detail_con clearfix">
    <div class="book_detail_pic fl"><img src="{% static book.image %}"></div>

    <div class="book_detail_list fr">
        <h3>{{ book.name }}</h3>
        <p>{{ book.desc }}</p>
        <div class="prize_bar">
            <span class="show_price">¥<em>{{ book.price }}</em></span>
            <span class="show_unit">单  位：{{ book.unit }}</span>
        </div>
        <div class="book_num clearfix">
            <div class="num_name fl">数 量：</div>
            <div class="num_add fl">
                <input type="text" class="num_show fl" value="1">
                <a href="javascript:;" class="add fr">+</a>
                <a href="javascript:;" class="minus fr">-</a>
            </div>
        </div>
        <div class="total">总价：<em>100元</em></div>
        <div class="operate_btn">
            {% csrf_token %}
            <a href="javascript:;" class="buy_btn">立即购买</a>
            <a href="javascript:;" books_id="{{ book.id }}" class="add_cart" id="add_cart">加入购物车</a>
            <a href="#" id="write-comment" class="comment">我要写评论</a>
        </div>
        <div style="display:flex;" id="comment-input" data-bookid="{{ book.id }}" data-userid="{{ request.session.passport_id }}">
            <div>
                <input type="text" placeholder="评论内容">
            </div>
            <div id="submit-comment">
                <button>
                    提交评论
                </button>
            </div>
        </div>
    </div>
</div>

<div class="main_wrap clearfix">
    <div class="l_wrap fl clearfix">
        <div class="new_book">
            <h3>新品推荐</h3>
            <ul>
                {% for book in books_li %}
                <li>
                    <a href="{% url 'books:detail'  book_id=book.id %}"><img src="{% static book.image %}"></a>
                    <h4><a href="{% url 'books:detail'  book_id=book.id %}">{{ book.name }}</a></h4>
                    <div class="prize">￥{{ book.price }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="r_wrap fr clearfix">
        <ul class="detail_tab clearfix">
            <li class="active">商品介绍</li>
            <li>评论</li>
        </ul>

        <div class="tab_content">
            <dl>
                <dt>商品详情：</dt>
                {# 不转译富文本编译器中的格式 #}
                <dd>{{ book.detail | safe }}</dd>
            </dl>
        </div>
    </div>
</div>
<div class="add_jump"></div>
{% endblock body %}
{% block bottomfiles %}
{#<script type="text/javascript" src="/static/js/jquery-1.12.2.js"></script>#}
<script type="text/javascript">
    //add_cart加入购物车按钮的的偏移量
    var $add_x = $('#add_cart').offset().top;
    var $add_y = $('#add_cart').offset().left;
    //顶端购物车展示框的偏移量
    var $to_x = $('#show_count').offset().top;
    var $to_y = $('#show_count').offset().left;

    {# 点击加入购物车按钮时触发的函数 #}
    $('#add_cart').click(function(){
        {# 获取商品id和商品数量 #}
        books_id = $(this).attr('books_id');
        books_count = $('.num_show').val();
        csrf = $('input[name="csrfmiddlewaretoken"]').val();
        params = {
            'books_id':books_id,
            'books_count':books_count,
            'csrfmiddlewaretoken':csrf
        };
        //发起请求,访问/cart/add/,进行购物车数据的添加
        $.post('/cart/add/',params,function (data) {
            if(data.res == 5){
                //添加成功
                $('.add_jump').css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
                $('.add_jump').stop().animate({
                    'left':$to_y+7,
                    'top':$to_x+7},
                    'fast',function(){
                        $('.add_jump').fadeOut('fast',function () {
                            //获取原有show_count的值
                            count = $('#show_count').html();
                            count = parseInt(count) + parseInt(books_count);
                            $('#show_count').html(count);
                        })
                    })
            }
            else {
                //添加失败
                alert(data.errmsg)
            }
        });
    });

{#    $.ajax({#}
{#        url:'/comment/comment/' + $('#comment-input').data('bookid'),#}
{#        success:function (res) {#}
{#            if(res.code == 200){#}
{#                var data = res.data;#}
{#                console.log(data);#}
{#                var div_head = '<div>';#}
{#                var div_tail = '</div>';#}
{#                var dom_element = '';#}
{#                for(i = 0; i < data.length; i++){#}
{#                    var head = '<div>';#}
{#                    var tail = '</div>';#}
{#                    var temp = head + '<span>' + data[i].user_id + '</span>' + '<br>' + '<span>' + data[i].content + '</span>' + tail;#}
{#                    dom_element += temp;#}
{#                }#}
{#                dom_element = div_head + dom_element + div_tail;#}
{#                $('#book_comment').append(dom_element);#}
{#            }#}
{#        }#}
{#    });#}

</script>
{% endblock bottomfiles %}

bookstore/templates/books/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-首页{% endblock title %}

{% block body %}
<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>
	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="/static/images/adv02.jpg" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
        {# 新书链接 #}
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in python_new %}
				<a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'books:list' type_id=1 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>
        {# 热销书链接 #}
		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
			<ul class="book_list fl">
                {% for book in python_hot %}
				<li>
                    {# 反向解析到商品详情页,把书籍的ID作为关键字参数传递给应用路由,在调用视图函数的时候作为参数传入 #}
					<h4><a href="{% url 'books:detail'  book_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail'  book_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in javascript_new %}
				<a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'books:list' type_id=2 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="book_list fl">
                {% for book in javascript_hot %}
				<li>
					<h4><a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in algorithms_new %}
				<a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'books:list' type_id=3 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner03.jpg"></div>
			<ul class="book_list fl">
                {% for book in algorithms_hot %}
				<li>
					<h4><a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in machinelearning_new %}
				<a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'books:list' type_id=4 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner04.jpg"></div>
			<ul class="book_list fl">
               {% for book in machinelearning_hot %}
				<li>
					<h4><a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in operatingsystem_new %}
				<a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'books:list' type_id=5 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner05.jpg"></div>
			<ul class="book_list fl">
               {% for book in operatingsystem_hot %}
				<li>
					<h4><a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in operatingsystem_new %}
				<a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'books:list' type_id=6 page=1 %}" class="book_more fr">查看更多 ></a>
		</div>
		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="/static/images/banner06.jpg"></div>
			<ul class="book_list fl">
               {% for book in database_hot %}
				<li>
					<h4><a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a></h4>
					<a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
{% endblock body %}

bookstore/templates/books/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}尚硅谷书城-商品列表{% endblock title %}

{# 导航块 #}
{% block navbar %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                <li><a href="#" class="python">Python</a></li>
                <li><a href="#" class="javascript">Javascript</a></li>
                <li><a href="#" class="algorithms">数据结构与算法</a></li>
                <li><a href="#" class="machinelearning">机器学习</a></li>
                <li><a href="#" class="operatingsystem">操作系统</a></li>
                <li><a href="#" class="database">数据库</a></li>
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">移动端书城</a></li>
            <li class="interval">|</li>
            <li><a href="">秒杀</a></li>
        </ul>
    </div>
</div>
{% endblock navbar %}

{% block body %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type_title }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in books_new %}
					<li>
						<a href="{% url 'books:detail' book_id=book.id%}"><img src="{% static book.image %}"></a>
						<h4><a href="{% url 'books:detail' book_id=book.id%}">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="/list/{{ type_id }}/1/" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="/list/{{ type_id }}/1/?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="/list/{{ type_id }}/1/?sort=hot" {% if sort == 'hot' %}class="active" {% endif %}>人气</a>
			</div>

			<ul class="book_type_list clearfix">
                {% for book in books_li %}
				<li>
					<a href="{% url 'books:detail' book_id=book.id %}"><img src="{% static book.image %}"></a>
					<h4><a href="{% url 'books:detail' book_id=book.id %}">{{ book.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ book.price }}</span>
						<span class="unit">/{{ book.unit }}</span>
						<a href="#" class="add_book" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
			<div class="pagenation">
                {% if books_li.has_previous %}
				    <a href="/list/{{ type_id }}/{{ books_li.previous_page_number }}/?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for index in pages %}
                    {% if index == books_li.number %}
                        <a href="/list/{{ type_id }}/{{ index }}/?sort={{ sort }}" class="active">{{ index }}</a>
                    {% else %}
                        <a href="/list/{{ type_id }}/{{ index }}/?sort={{ sort }}">{{ index }}</a>
                    {% endif %}
                {% endfor %}
                {% if books_li.has_next %}
				    <a href="/list/{{ type_id }}/{{ books_li.next_page_number }}/?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock body %}